inherit_gem:
  rubocop-aha: lib/config.yml

AllCops:
  Exclude:
    - bin/**
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
  TargetRubyVersion: 2.6
  DisplayCopNames: true

RSpec/LetSetup:
  Enabled: false
