AllCops:
  Exclude:
    - bin/**
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature']
  Exclude:
    - config/routes.rb
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
